# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files", "--skip", "__init__.py"]
        files: ^dodiscover/
  - repo: https://github.com/pre-commit/mirrors-mypy 
    rev: "v2.3.1"
    hooks:
      - id: mypy
        name: mypy (dodiscover)
        args: ["--config-file", "pyproject.toml"]
        files: ^dodiscover/
  - repo: https://github.com/pre-commit/mirrors-mypy 
    rev: "v2.3.1"
    hooks:
      - id: mypy
        name: mypy (tests)
        args: ["--config-file", "pyproject.toml"]
        files: ^tests/

